#!/bin/sh /etc/rc.common
START=66
USE_PROCD=1

FLAG=/var/wakey_updated.flag

start_service() {
  [ -f "$FLAG" ] && return

  procd_open_instance
  procd_set_param command /etc/ldlda_help/update_wakey.sh
  procd_set_param respawn 0 0 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  :  # no-op
}

post_service() {
  touch "$FLAG"
}
