#!/bin/sh /etc/rc.common
START=66
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /bin/sh -c \
    'while ! /etc/ldlda_help/update_wakey.sh; do sleep 5; done'
  procd_set_param respawn 9999 15 1
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  : # no-op
}
