#!/bin/sh /etc/rc.common
# Simple helper to update tailscale before its own init runs
# Provides: update_tailscale
# Required-Start: $network
# Required-Stop:
# Default-Start:  S  # earliest boot stage
# Default-Stop:
# Short-Description: Pre-flight Tailscale update

START=50  # Run before Tailscale (typically START~80)
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /bin/sh -c \
  'while ! /etc/ldlda_help/update_tailscale.sh; do sleep 5; done'
  # procd_set_param respawn 0 0 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  : # one-shot
}
