#!/bin/sh /etc/rc.common

START=66  # Run after the resolvconf swap
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /etc/ldlda_help/update_wakey.sh
  procd_set_param respawn 0 0 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  : # one-shot
}

# Test manually:
#   chmod +x /etc/init.d/update_wakey
#   /etc/init.d/update_wakey start
# Or enable on boot:
#   /etc/init.d/update_wakey enable
