#!/bin/sh /etc/rc.common
# OpenWrt init script

START=99
USE_PROCD=1

NAME=wakey
BIN=/root/.bin/wakey

start_service() {
    procd_open_instance
    procd_set_param command "$BIN"
    procd_set_param respawn 5 1 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    : # procd manages the process; nothing to do here
}
