[package]
name = "wakey"
version = "0.0.0"
edition = "2024"
publish = ["gitea"]

[dependencies]
axum = "0.8.4"
color-eyre = "0.6.5"
futures = "0.3.31"
macaddr = "1.0.1"
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["fs", "process", "rt-multi-thread"] }

[profile.release]
opt-level = "z"
strip = true