[package]
name = "wakey"
version = "0.1.7"
edition = "2024"
publish = ["gitea"]

[dependencies]
anyhow = "1"
axum = { version = "0", features = ["macros"] }
axum-extra = { version = "0", features = ["query"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
color-eyre = "0"
comfy-table = "7"
futures = "0"
macaddr = { version = "1", features = ["serde", "serde_std"] }
serde = { version = "1", features = ["derive"] }
serde_html_form = "0"
serde_json = "1"
tokio = { version = "1", features = [
    "fs",
    "process",
    "rt-multi-thread",
    "io-util",
    "macros",
] }
tower-http = { version = "0", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
urlencoding = "2"
wakey-core = { path = "wakey-core" }
wakey-linux = { path = "wakey-linux" }

[profile.release]
opt-level = "z"
strip = true

[features]
default = ["very-smart-parsing"]
very-smart-parsing = [
] # this is the a-bit-redundant parse thing that copilot made

[workspace]
members = ["ipjs", "wakey-agent", "wakey-core", "wakey-linux"]

[dependencies.lda-ipjs]
path = "ipjs"
registry = "gitea"
version = "*"
