[package]
name = "wakey"
version = "0.3.0"
edition = "2024"
publish = ["gitea"]

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4", features = ["derive"] }
color-eyre = "0"
comfy-table = "7"
futures = "0"
macaddr = { version = "1", features = ["serde", "serde_std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
    "fs",
    "process",
    "rt-multi-thread",
    "io-util",
    "macros",
    "time",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[profile.release]
opt-level = "z"
strip = true

[workspace]
members = ["ipjs", "wakey-agent", "wakey-control-plane", "wakey-core", "wakey-linux"]

[workspace.dependencies]
anyhow = "1"
macaddr = { version = "1", features = ["serde", "serde_std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
    "fs",
    "process",
    "rt-multi-thread",
    "io-util",
    "macros",
    "time",
] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }

[dependencies.lda-ipjs]
path = "ipjs"
registry = "gitea"
version = "0"

[dependencies.wakey-core]
path = "wakey-core"
registry = "gitea"
version = "0"

[dependencies.wakey-linux]
path = "wakey-linux"
registry = "gitea"
version = "0"
