[package]
name = "wakey-linux"
version = "0.2.0"
edition = "2024"
publish = ["gitea"]

[dependencies]
anyhow = "1"
futures = "0"
macaddr = { version = "1", features = ["serde", "serde_std"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "net", "rt", "sync"] }
wakey-core = { path = "../wakey-core", registry = "gitea", version = "0"}

[dependencies.lda-ipjs]
path = "../ipjs"
registry = "gitea"
version = "0"
features = ["experimental-nl"]
