[target.armv7-unknown-linux-musleabihf]
linker = "rust-lld"

[build]
target = "armv7-unknown-linux-musleabihf"

[alias]
ldabr = "b -r --target=target.armv7-unknown-linux-musleabihf"
t = "test -- --nocapture --test-threads=1"
tdebug = "test -- --nocapture --test-threads=1 --show-output"