[package]
name = "wakey-agent"
version = "0.2.3"
edition = "2024"
publish = ["gitea"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
http = "1"
macaddr = { version = "1", features = ["serde", "serde_std"] }
nix = { version = "0.31", default-features = false, features = [
    "signal",
    "process",
] }
reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "rustls",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
    "fs",
    "macros",
    "rt-multi-thread",
    "time",
    "signal",
    "sync",
] }
tokio-tungstenite = { version = "0.29", features = ["rustls-tls-webpki-roots"] }
toml = "1.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "time",
] }
time = { version = "0.3", features = ["formatting", "local-offset"] }
url = "2"
wakey = { path = "..", registry = "gitea", version = "0" }
wakey-core = { path = "../wakey-core", registry = "gitea", version = "0" }
